admin_meilisearch_index_index:
  path: /admin/meilisearch/index
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchIndexController::indexAction'

admin_meilisearch_index_products:
  path: /admin/meilisearch/index-products
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchIndexController::indexProductsAction'

admin_meilisearch_index_delete:
  path: /admin/meilisearch/index/{uid}/delete
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchIndexController::deleteAction'

admin_meilisearch_index_bulk_delete:
  path: /admin/meilisearch/index/bulk-delete
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchIndexController::bulkDeleteAction'

admin_meilisearch_index_flush:
  path: /admin/meilisearch/index/{uid}/flush
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchIndexController::flushAction'

admin_meilisearch_index_bulk_flush:
  path: /admin/meilisearch/index/bulk-flush
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchIndexController::bulkFlushAction'

admin_meilisearch_configuration_index:
  path: /admin/meilisearch/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchConfigurationController::indexAction'

admin_meilisearch_stats_index:
  path: /admin/meilisearch/stats
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchStatsController::indexAction'
