admin_meilisearchconfiguration_index:
  path: /admin/meilisearch/configuration
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchConfigurationController::indexAction'

admin_meilisearchconfiguration_index_products:
  path: /admin/meilisearch/index-products
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchConfigurationController::indexProductsAction'

admin_meilisearch_stats_index:
  path: /admin/meilisearch/stats
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\MeiliSearch\Controller\Admin\MeiliSearchStatsController::indexAction'