name: PrestaFlow tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  prestaflow:
    name: PrestaFlow e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Create .env
        run: |
          echo "PRESTAFLOW_FO_URL=${{ secrets.PRESTAFLOW_FO_URL }}" >> .env
          echo "PRESTAFLOW_PS_VERSION=9.0.3" >> .env
          echo "PRESTAFLOW_LOCALE=fr" >> .env
          echo "PRESTAFLOW_PREFIX_LOCALE=true" >> .env
          echo "PRESTAFLOW_HEADLESS=true" >> .env

      - name: Run PrestaFlow tests
        run: composer prestaflow
